Configure mTLS for file-transfer and c8y proxy
Signed-off-by: Didier Wenzek <didier.wenzek@free.fr>

diff --git a/commands/bootstrap b/commands/bootstrap
--- a/commands/bootstrap
+++ b/commands/bootstrap
@@ -7,7 +7,7 @@ RENEW_CERT=1
 WEBSITE_PAGE="device-info"
 SSH_USER=
 MTLS=0
-ROOT_DEVICE=
+MAIN_DEVICE=
 SCAN=${SCAN:-0}
 PATTERN="${PATTERN:-.+}"
 BOOTSTRAP_TYPE="${BOOTSTRAP_TYPE:-}"
@@ -39,11 +39,11 @@ Type: --mtls
 4. Create a local certificate for the main device signed by its signing certificate (as the latter will be trusted by all child-devices)
 
 
-Type: --mtls --root-device <ROOT_DEVICE>
-1. Configure the device as a child device and enforce mTLS for all connections to the root device
-2. Create a signing certificate for the root device (if not already done) (stored on the host)
-3. Configure the device to trust its root device signing certificate
-4. Create a local certificate for the child device signed by the root device signing certificate
+Type: --mtls --main-device <MAIN_DEVICE>
+1. Configure the device as a child device and enforce mTLS for all connections to the main device
+2. Create a signing certificate for the main device (if not already done) (stored on the host)
+3. Configure the device to trust its main device signing certificate
+4. Create a local certificate for the child device signed by the main device signing certificate
 
 
 USAGE
@@ -60,7 +60,7 @@ FLAGS
   --page <STRING>                   Which Device Management page to open. Defaults to device-info
   --type <local-ca|self-signed>     Certificate signing method. Accepts local-ca (default), self-signed
   --mtls                            Enable mTLS for all local connections over MQTT and HTTP
-  --root-device <ROOT_DEVICE>       Root device hostname or ip address to connect to via ssh. This is only used when enabling mTLS on a child device.
+  --main-device <MAIN_DEVICE>       Main device hostname or ip address to connect to via ssh. This is only used when enabling mTLS on a child device.
   --scan                            Bootstrap devices found by a scan
   --pattern <REGEX>                 Only include devices which match the given pattern (only applies when piping or scanning devices)
   --verbose                         Enable verbose logging
@@ -86,7 +86,7 @@ c8y tedge bootstrap root@mydevice.local --type self-signed
 c8y tedge bootstrap root@mydevice.local --mtls
 
 # Bootstrap a child device enabling mTLS
-c8y tedge bootstrap root@my-child-device.local --mtls --root-device root@mydevice.local
+c8y tedge bootstrap root@my-child-device.local --mtls --main-device root@mydevice.local
 
 # Bootstrap a device via ssh but don't open the website
 c8y tedge bootstrap root@mydevice.local --skip-website
@@ -125,8 +125,8 @@ while [ $# -gt 0 ]; do
         --mtls)
             ENABLE_MTLS=1
             ;;
-        --root-device)
-            ROOT_DEVICE="$2"
+        --main-device)
+            MAIN_DEVICE="$2"
             shift
             ;;
         --scan)
@@ -284,7 +284,7 @@ EOF
     cat "$CA_CERT_FILE" >> "$DEVICE_CERT_CHAIN"
 
     # Copy cert to device
-    scp "$DEVICE_CERT_CHAIN" "$TARGET:/tmp/${DEVICE_ID}.crt"
+    "${SCP_CMD}" "$DEVICE_CERT_CHAIN" "$TARGET" "/tmp/${DEVICE_ID}.crt"
     "${EXEC_CMD[@]}" "$TARGET" sudo mv "/tmp/${DEVICE_ID}.crt" "$DEVICE_CERT_PATH"
     "${EXEC_CMD[@]}" "$TARGET" sudo chown mosquitto:root "$DEVICE_CERT_PATH"
     "${EXEC_CMD[@]}" "$TARGET" sudo chmod 644 "$DEVICE_CERT_PATH"
@@ -342,21 +342,21 @@ create_self_signed() {
 #
 # The associated private key is stored on the host running the `c8y tedge` command - not the main device.
 create_signing_cert() {
-    ROOT_DEVICE_ID=$1
-    if [ -z "$ROOT_DEVICE_ID" ]; then
-        echo "mTLS cannot be enabled without an id for the root device" >&2
+    MAIN_DEVICE_ID=$1
+    if [ -z "$MAIN_DEVICE_ID" ]; then
+        echo "mTLS cannot be enabled without an id for the main device" >&2
         exit 1
     fi
 
     SIGNING_CERT_DIR="${HOME}/.tedge/device-signing-certs"
-    SIGNING_CERT_NAME="${ROOT_DEVICE_ID}-local-ca"
+    SIGNING_CERT_NAME="${MAIN_DEVICE_ID}-local-ca"
     SIGNING_CERT_FILE="${SIGNING_CERT_DIR}/${SIGNING_CERT_NAME}.crt"
     SIGNING_CERT_KEY="${SIGNING_CERT_DIR}/${SIGNING_CERT_NAME}.key"
     CA_EXPIRE_DAYS="${CA_EXPIRE_DAYS:-365}"
 
     mkdir -p "$SIGNING_CERT_DIR"
 
-    if [ -f "$SIGNING_CERT_FILE" ] && [ -f "$SIGNING_CERT_KEY=" ]; then
+    if [ -f "$SIGNING_CERT_FILE" ] && [ -f "$SIGNING_CERT_KEY" ]; then
         echo "Using existing device local CA certificate: $SIGNING_CERT_FILE" >&2
     else
         echo "Creating new device local CA certificate: $SIGNING_CERT_FILE" >&2
@@ -372,28 +372,39 @@ create_signing_cert() {
     fi
 
     # Make the signing certificate trusted by the device
-    scp "$SIGNING_CERT_FILE" "$TARGET:/tmp/${SIGNING_CERT_NAME}.crt"
+    "${SCP_CMD}" "$SIGNING_CERT_FILE" "$TARGET" "/tmp/${SIGNING_CERT_NAME}.crt"
     "${EXEC_CMD[@]}" "$TARGET" sudo mv "/tmp/${SIGNING_CERT_NAME}.crt" "/usr/local/share/ca-certificates"
     "${EXEC_CMD[@]}" "$TARGET" sudo update-ca-certificates
 }
 
-# Create a certificate that is trusted by all the entities attached to a root device
+# Create a certificate that is trusted by all the entities attached to a main device
 #
 # This certificate is created on the target device,
-# but signed on the host running the `c8y tedge` command on behalf of the root device.
+# but signed on the host running the `c8y tedge` command on behalf of the main device.
 create_local_cert() {
-    ROOT_DEVICE_ID=$1
+    MAIN_DEVICE_ID=$1
     SERVICE=$2
-    if [ -z "$ROOT_DEVICE_ID" ]; then
-        echo "mTLS cannot be enabled without an id for the root device" >&2
+    if [ -z "$MAIN_DEVICE_ID" ]; then
+        echo "mTLS cannot be enabled without an id for the main device" >&2
         exit 1
     fi
     if [ -z "$SERVICE" ]; then
         SERVICE=main-agent
     fi
 
+    # Prepare required info for subjectAltName
+    TARGET_DNS=$("${EXEC_CMD[@]}" "$TARGET" hostname 2>/dev/null || true)
+    if [ -z "$TARGET_DNS" ]; then
+        TARGET_DNS=$(echo "$TARGET" | sed -E 's/.*@(\S+)/\1/')
+    fi
+    TARGET_IP=$("${EXEC_CMD[@]}" "$TARGET" ip route get 8.8.8.8 2>/dev/null | sed -E 's/.*src (\S+) .*/\1/;t;d' 2>/dev/null || true)
+    if [ -z "$TARGET_IP" ]; then
+        TARGET_IP=$(echo "$TARGET" | sed -E 's/.*@(\S+)/\1/')
+    fi
+
+    # Prepare cert files
     SIGNING_CERT_DIR="${HOME}/.tedge/device-signing-certs"
-    SIGNING_CERT_NAME="${ROOT_DEVICE_ID}-local-ca"
+    SIGNING_CERT_NAME="${MAIN_DEVICE_ID}-local-ca"
     SIGNING_CERT_FILE="${SIGNING_CERT_DIR}/${SIGNING_CERT_NAME}.crt"
     SIGNING_CERT_KEY="${SIGNING_CERT_DIR}/${SIGNING_CERT_NAME}.key"
     CA_EXPIRE_DAYS="${CA_EXPIRE_DAYS:-365}"
@@ -420,7 +431,7 @@ create_local_cert() {
         "${EXEC_CMD[@]}" "$TARGET" $SUDO openssl req \
             -key "$LOCAL_CERT_KEY" \
             -new \
-            -subj "/O=thin-edge/OU=${DEVICE_ID}/SN=${SERVICE}/CN=localhost"
+            -subj "/O=thin-edge/OU=${DEVICE_ID}/CN=${SERVICE}"
     )
 
     # Sign the CSR
@@ -431,15 +442,12 @@ extendedKeyUsage = clientAuth
 EOF
     )
     else
-    USER="${SSH_USER:-root}"
-    WITHOUT_USER_PREFIX="${USER}@"
-    HOST=${TARGET#"$WITHOUT_USER_PREFIX"}
     CERT_EXT=$(cat << EOF
 authorityKeyIdentifier=keyid
 basicConstraints=CA:FALSE
 keyUsage = digitalSignature, keyAgreement
 extendedKeyUsage = serverAuth, clientAuth
-subjectAltName=DNS:${HOST},DNS:localhost
+subjectAltName = DNS:${TARGET_DNS},IP:${TARGET_IP},DNS:localhost,IP:127.0.0.1
 EOF
     )
     fi
@@ -458,11 +466,103 @@ EOF
     cat "$SIGNING_CERT_FILE" >> "$DEVICE_CERT_CHAIN"
 
     # Copy cert to device
-    scp "$DEVICE_CERT_CHAIN" "$TARGET:/tmp/${LOCAL_CERT_NAME}.crt"
-    "${EXEC_CMD[@]}" "$TARGET" sudo mv "/tmp/${LOCAL_CERT_NAME}.crt" "$LOCAL_CERT_FILE"
-    "${EXEC_CMD[@]}" "$TARGET" sudo chown tedge:root "$LOCAL_CERT_FILE"
-    "${EXEC_CMD[@]}" "$TARGET" sudo chmod 644 "$LOCAL_CERT_FILE"
+    "${SCP_CMD}" "$DEVICE_CERT_CHAIN" "$TARGET" "/tmp/${LOCAL_CERT_NAME}.crt"
+    "${EXEC_CMD[@]}" "$TARGET" "$SUDO" mv "/tmp/${LOCAL_CERT_NAME}.crt" "$LOCAL_CERT_FILE"
+    "${EXEC_CMD[@]}" "$TARGET" "$SUDO" chown tedge:root "$LOCAL_CERT_FILE"
+    "${EXEC_CMD[@]}" "$TARGET" "$SUDO" chmod 644 "$LOCAL_CERT_FILE"
+
+    case "$SERVICE" in
+        main-agent)
+            configure_mtls_main_agent "$TARGET_IP" "$TARGET_DNS" "$LOCAL_CERT_FILE" "$LOCAL_CERT_KEY"
+            ;;
+        c8y-mapper)
+            configure_mtls_c8y_mapper "$TARGET_IP" "$TARGET_DNS" "$LOCAL_CERT_FILE" "$LOCAL_CERT_KEY"
+            ;;
+        child-agent)
+	    # GET IP and DNS of the main device
+	    MAIN_DEVICE_DNS=$("${EXEC_CMD[@]}" "$MAIN_DEVICE" hostname 2>/dev/null || true)
+            if [ -z "$MAIN_DEVICE_DNS" ]; then
+                MAIN_DEVICE_DNS=$(echo "$MAIN_DEVICE" | sed -E 's/.*@(\S+)/\1/')
+            fi
+            MAIN_DEVICE_IP=$("${EXEC_CMD[@]}" "$MAIN_DEVICE" ip route get 8.8.8.8 2>/dev/null | sed -E 's/.*src (\S+) .*/\1/;t;d' 2>/dev/null || true)
+            if [ -z "$MAIN_DEVICE_IP" ]; then
+                MAIN_DEVICE_IP=$(echo "$MAIN_DEVICE" | sed -E 's/.*@(\S+)/\1/')
+            fi
+            configure_mtls_child_agent "$MAIN_DEVICE_IP" "$MAIN_DEVICE_DNS" "$LOCAL_CERT_FILE" "$LOCAL_CERT_KEY"
+            ;;
+        *)
+            ;;
+    esac
 }
+
+# configure tegde-agent on the main device
+configure_mtls_main_agent() {
+    TARGET_IP="$1"
+    TARGET_DNS="$2"
+    LOCAL_CERT_FILE="$3"
+    LOCAL_CERT_KEY="$4"
+
+    # tedge-agent acts as a server for file-transfer	
+    "${EXEC_CMD[@]}" "$TARGET" $SUDO tedge config set http.bind.address "$TARGET_IP"
+    "${EXEC_CMD[@]}" "$TARGET" $SUDO tedge config set http.bind.port "8000"
+    "${EXEC_CMD[@]}" "$TARGET" $SUDO tedge config set http.cert_path "$LOCAL_CERT_FILE"
+    "${EXEC_CMD[@]}" "$TARGET" $SUDO tedge config set http.key_path "$LOCAL_CERT_KEY"
+    "${EXEC_CMD[@]}" "$TARGET" $SUDO tedge config set http.ca_path /etc/ssl/certs
+
+    # tedge-agent is a client of c8y-proxy	
+    "${EXEC_CMD[@]}" "$TARGET" $SUDO tedge config set c8y.proxy.client.host "$TARGET_DNS"
+    "${EXEC_CMD[@]}" "$TARGET" $SUDO tedge config set c8y.proxy.client.port "8001"
+
+    # apply the new config
+    echo "Restart tedge-agent on ${TARGET_DNS}" >&2
+    "${EXEC_CMD[@]}" "$TARGET" $SUDO systemctl restart tedge-agent
+}
+
+configure_mtls_c8y_mapper() {
+    TARGET_IP="$1"
+    TARGET_DNS="$2"
+    LOCAL_CERT_FILE="$3"
+    LOCAL_CERT_KEY="$4"
+
+    # c8y-mapper acts as a server for c8y proxy
+    "${EXEC_CMD[@]}" "$TARGET" $SUDO tedge config set c8y.proxy.bind.address "$TARGET_IP"
+    "${EXEC_CMD[@]}" "$TARGET" $SUDO tedge config set c8y.proxy.bind.port "8001"
+    "${EXEC_CMD[@]}" "$TARGET" $SUDO tedge config set c8y.proxy.cert_path "$LOCAL_CERT_FILE"
+    "${EXEC_CMD[@]}" "$TARGET" $SUDO tedge config set c8y.proxy.key_path "$LOCAL_CERT_KEY"
+    "${EXEC_CMD[@]}" "$TARGET" $SUDO tedge config set c8y.proxy.ca_path /etc/ssl/certs
+
+    # c8y-mapper is a client of file-transfer
+    "${EXEC_CMD[@]}" "$TARGET" $SUDO tedge config set http.client.host "$TARGET_DNS"
+    "${EXEC_CMD[@]}" "$TARGET" $SUDO tedge config set http.client.port "8000"
+    "${EXEC_CMD[@]}" "$TARGET" $SUDO tedge config set http.client.auth.cert_file "$LOCAL_CERT_FILE"
+    "${EXEC_CMD[@]}" "$TARGET" $SUDO tedge config set http.client.auth.key_file "$LOCAL_CERT_KEY"
+
+    # apply the new config
+    echo "Restart tedge-mapper-c8y on ${TARGET_DNS}" >&2
+    "${EXEC_CMD[@]}" "$TARGET" $SUDO systemctl restart tedge-mapper-c8y
+}
+
+configure_mtls_child_agent() {
+    MAIN_DEVICE_IP="$1"
+    MAIN_DEVICE_DNS="$2"
+    LOCAL_CERT_FILE="$3"
+    LOCAL_CERT_KEY="$4"
+
+    # child_agent is a client of c8y-proxy	
+    "${EXEC_CMD[@]}" "$TARGET" $SUDO tedge config set c8y.proxy.client.host "$MAIN_DEVICE_DNS"
+    "${EXEC_CMD[@]}" "$TARGET" $SUDO tedge config set c8y.proxy.client.port "8001"
+
+    # child_agent is a client of file-transfer
+    "${EXEC_CMD[@]}" "$TARGET" $SUDO tedge config set http.client.host "$MAIN_DEVICE_DNS"
+    "${EXEC_CMD[@]}" "$TARGET" $SUDO tedge config set http.client.port "8000"
+    "${EXEC_CMD[@]}" "$TARGET" $SUDO tedge config set http.client.auth.cert_file "$LOCAL_CERT_FILE"
+    "${EXEC_CMD[@]}" "$TARGET" $SUDO tedge config set http.client.auth.key_file "$LOCAL_CERT_KEY"
+
+    # apply the new config
+    echo "Restart tedge-agent on ${TARGET_DNS}" >&2
+    "${EXEC_CMD[@]}" "$TARGET" $SUDO systemctl restart tedge-agent
+}
+
 
 get_device_id() {
     # Get identity (stop on first non empty value)
@@ -501,12 +601,21 @@ EXEC_CMD=(
     -n
 )
 
+remote_scp() {
+    scp "$1" "$2:$3"
+}
+
+SCP_CMD=remote_scp
+
 do_action() {
     if [ $# -gt 0 ]; then
         TARGET="$1"
     fi
+    if [ -n "$MAIN_DEVICE" ]; then
+        MAIN_DEVICE_ID=$(get_device_id "$MAIN_DEVICE")
+    fi
     if [ -n "$SSH_USER" ]; then
-        TARGET="$SSH_USER@$TARGET"
+         TARGET="$SSH_USER@$TARGET"
     fi
 
     # Don't use sudo if the user is root
@@ -572,16 +681,15 @@ do_action() {
             echo "Missing dependency: openssl is not installed" >&2
             exit 1
         fi
-        if [ -z "$ROOT_DEVICE" ]; then
+        if [ -z "$MAIN_DEVICE" ]; then
             # enabling mTLS on the main device
             create_signing_cert "$DEVICE_ID"
             create_local_cert "$DEVICE_ID" main-agent
             create_local_cert "$DEVICE_ID" c8y-mapper
         else
-            # enabling mTLS on a child device
-            ROOT_DEVICE_ID=$(get_device_id "$ROOT_DEVICE")
-            create_signing_cert "$ROOT_DEVICE_ID"
-            create_local_cert "$ROOT_DEVICE_ID" child-agent
+            # enabling mTLS on a child devicez
+            create_signing_cert "$MAIN_DEVICE_ID"
+            create_local_cert "$MAIN_DEVICE_ID" child-agent
         fi
     fi
 
