feat: add support for Cumulocity CA

diff --git a/commands/bootstrap b/commands/bootstrap
--- a/commands/bootstrap
+++ b/commands/bootstrap
@@ -14,6 +14,8 @@ BOOTSTRAP_TYPE="${BOOTSTRAP_TYPE:-}"
 SUDO=${SUDO:-}
 OFFLINE_MODE=${OFFLINE_MODE:-0}
 REMOVE_KNOWN_HOST_ENTRY_ON_FAILURE=${REMOVE_KNOWN_HOST_ENTRY_ON_FAILURE:-1}
+DEVICE_CODE=${DEVICE_CODE:-}
+DEVICE_TYPE="${DEVICE_TYPE:-thin-edge.io}"
 
 usage() {
     EXAMPLES=$(examples 2>&1)
@@ -62,6 +64,7 @@ FLAGS
   --skip-website                    Don't open the Cumulocity IoT Device Management application
   --page <STRING>                   Which Device Management page to open. Defaults to device-info
   --type <local-ca|self-signed>     Certificate signing method. Accepts local-ca (default), self-signed
+  --code <STRING>                   Cumulocity CA device code used for one-time enrolment
   --mtls                            Enable mTLS for all local connections over MQTT and HTTP
   --main-device <MAIN_DEVICE>       Main device hostname or ip address to connect to via ssh. This is only used when enabling mTLS on a child device.
   --scan                            Bootstrap devices found by a scan
@@ -101,6 +104,9 @@ c8y tedge bootstrap root@mydevice.local --skip-website
 # Bootstrap any devices found during a scan
 c8y tedge bootstrap --ssh-user root --scan --pattern "rpi3"
 
+# Bootstrap device using Cumulocity CA
+c8y tedge bootstrap --type c8y-ca root@mydevice.local
+
 EOT
 }
 
@@ -138,6 +144,11 @@ while [ $# -gt 0 ]; do
             ;;
         --type)
             BOOTSTRAP_TYPE="$2"
+            shift
+            ;;
+        --code)
+            # Only used for Cumulocity CA
+            DEVICE_CODE="$2"
             shift
             ;;
         --mtls)
@@ -756,28 +767,6 @@ configure_mtls_mqtt_client() {
     "${EXEC_CMD[@]}" "$TARGET" $SUDO tedge config set mqtt.client.auth.key_file "$LOCAL_CERT_KEY"
 }
 
-c8y_bulk_registration() {
-    EXTERNAL_ID="$1"
-    DEVICE_TYPE="thin-edge.io"
-    if [ $# -gt 1 ]; then
-        DEVICE_TYPE="$2"
-    fi
-
-    REG_FILE="/tmp/${EXTERNAL_ID}.csv"
-
-    cat << EOT > "$REG_FILE"
-"ID","AUTH_TYPE","TYPE","NAME","com_cumulocity_model_Agent.active"
-"$EXTERNAL_ID",CERTIFICATES,"$DEVICE_TYPE","$EXTERNAL_ID",true
-EOT
-
-    echo "Manually registering device: $EXTERNAL_ID (type=$DEVICE_TYPE)" >&2
-    if ! c8y api POST devicecontrol/bulkNewDeviceRequests --file "$REG_FILE" --force; then
-        echo "Warning: Failed to manually register device (via c8y bulk registration API): $EXTERNAL_ID" >&2
-        exit 1
-    fi
-    rm -f "$REG_FILE"
-}
-
 get_device_id() {
     # Get identity (stop on first non empty value)
     target="$1"
@@ -947,6 +936,19 @@ do_action() {
                         create_ca
                         create_remote_cert
                         ;;
+                    c8y-ca)
+                        if [ -z "$DEVICE_CODE" ]; then
+                            # generate random code
+                            DEVICE_CODE=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 32; echo)
+                        fi
+
+                        if ! c8y deviceregistration register-ca --id "$DEVICE_ID" --type "$DEVICE_TYPE" --one-time-password "$DEVICE_CODE" --force; then
+                            echo "Failed to register device" >&2
+                            exit 1
+                        fi
+
+                        "${EXEC_CMD[@]}" "$TARGET" $SUDO tedge cert download c8y --retry-every 5s --max-timeout 5m --device-id "$DEVICE_ID" --token "$DEVICE_CODE" 2>/dev/null
+                        ;;
                     *)
                         echo "Unknown bootstrapping method" >&2
                         exit 1
@@ -959,7 +961,10 @@ do_action() {
             echo "Bootstrapping thin-edge.io in OFFLINE mode" >&2
 
             # Register device via c8y bulk registration api because "tedge connect c8y" doesn't do it
-            c8y_bulk_registration "$DEVICE_ID"
+            if ! c8y deviceregistration register-external-ca --id "$DEVICE_ID" --type "$DEVICE_TYPE" --force; then
+                echo "Failed to register device" >&2
+                exit 1
+            fi
 
             if ! "${EXEC_CMD[@]}" "$TARGET" $SUDO PATH="$REMOTE_PATH" tedge connect c8y --offline; then
                 echo "Offline mode requires thin-edge.io >= 1.1.0. Please upgrade and try again" >&2
