manually register a device with c8y in offline mode to ensure device exists on first connection

diff --git a/commands/bootstrap b/commands/bootstrap
--- a/commands/bootstrap
+++ b/commands/bootstrap
@@ -733,6 +733,28 @@ configure_mtls_mqtt_client() {
     "${EXEC_CMD[@]}" "$TARGET" $SUDO tedge config set mqtt.client.auth.key_file "$LOCAL_CERT_KEY"
 }
 
+c8y_bulk_registration() {
+    EXTERNAL_ID="$1"
+    DEVICE_TYPE="thin-edge.io"
+    if [ $# -gt 1 ]; then
+        DEVICE_TYPE="$2"
+    fi
+
+    REG_FILE="/tmp/${EXTERNAL_ID}.csv"
+
+    cat << EOT > "$REG_FILE"
+"ID","AUTH_TYPE","TYPE","NAME","com_cumulocity_model_Agent.active"
+"$EXTERNAL_ID",CERTIFICATES,"$DEVICE_TYPE","$EXTERNAL_ID",true
+EOT
+
+    echo "Manually registering device: $EXTERNAL_ID (type=$DEVICE_TYPE)" >&2
+    if ! c8y api POST devicecontrol/bulkNewDeviceRequests --file "$REG_FILE" --force; then
+        echo "Warning: Failed to manually register device (via c8y bulk registration API): $EXTERNAL_ID" >&2
+        exit 1
+    fi
+    rm -f "$REG_FILE"
+}
+
 get_device_id() {
     # Get identity (stop on first non empty value)
     target="$1"
@@ -870,6 +892,10 @@ do_action() {
         # In offline mode, just configure the bridge, do not test the connection as the device may not have internet
         if [ "$OFFLINE_MODE" = 1 ]; then
             echo "Bootstrapping thin-edge.io in OFFLINE mode" >&2
+
+            # Register device via c8y bulk registration api because "tedge connect c8y" doesn't do it
+            c8y_bulk_registration "$DEVICE_ID"
+
             if ! "${EXEC_CMD[@]}" "$TARGET" $SUDO PATH="$REMOTE_PATH" tedge connect c8y --offline; then
                 echo "Offline mode requires thin-edge.io >= 1.1.0. Please upgrade and try again" >&2
                 exit 1
