feat(bootstrap): check for invalid flags and throw an error if detected

diff --git a/commands/bootstrap b/commands/bootstrap
--- a/commands/bootstrap
+++ b/commands/bootstrap
@@ -153,6 +153,11 @@ while [ $# -gt 0 ]; do
         --skip-renew-cert)
             RENEW_CERT=0
             ;;
+        --*|-*)
+            printf '\nERROR: Unknown flag. %s\n\n' "$1" >&2
+            usage
+            exit 1
+            ;;
         *)
             if [ -z "$TARGET" ]; then
                 TARGET="$1"
diff --git a/commands/bootstrap-container b/commands/bootstrap-container
--- a/commands/bootstrap-container
+++ b/commands/bootstrap-container
@@ -99,6 +99,11 @@ while [ $# -gt 0 ]; do
             set -x
             export C8Y_SETTINGS_DEFAULTS_DEBUG="true"
             ;;
+        --*|-*)
+            printf '\nERROR: Unknown flag. %s\n\n' "$1" >&2
+            usage
+            exit 1
+            ;;
         *)
             if [ -z "$TARGET" ]; then
                 TARGET="$1"
